[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "cp prisma/schema.prod.prisma prisma/schema.prisma",
  "npx prisma generate",
  "npx prisma db push --accept-data-loss",
  "node prisma/seed.prod.js"
]
dependsOn = ["install"]

[start]
cmd = "node src/index.js"
